#!/bin/bash
declare -A hosts; while IFS=$'\t' read -r host _; do ((hosts[$host]++)); done < "$1"; for host in "${!hosts[@]}"; do printf "%s\t%d\n" "$host" "${hosts[$host]}"; done | sort -nrk2 | head -n 11
